# Kitchen-sink MediaStack: every supported app, with auto-injected NFS media volumes.
#
# NFS server
# ----------
# The operator deploys an in-cluster NFS server by default and auto-injects
# the right NFS mounts into each app:
#
#   Plex / Jellyfin          /movies  /tv  /music  /movies-4k  /tv-4k
#   Sonarr (standard)        /tv
#   Sonarr-4k                /tv       ← container path, but NFS server at /nfsshare/tv-4k
#   Radarr (standard)        /movies
#   Radarr-4k                /movies   ← container path, but NFS server at /nfsshare/movies-4k
#   Lidarr                   /music
#   SABnzbd / Transmission   /movies  /tv  /music  /movies-4k  /tv-4k
#
# No manual nfsMounts config is needed for these apps.
# Other apps (Prowlarr, Overseerr, Maintainerr, …) receive no NFS mounts
# unless you add them explicitly.
#
# To use an external NFS server instead of the in-cluster one:
#
#   nfs:
#     externalServer: nas.home.arpa
#     externalPath: /volume1    # prepended to all media paths
#
# To disable NFS entirely:
#
#   nfs:
#     enabled: false
#
# To override individual media subpaths (defaults shown):
#
#   nfs:
#     moviesPath: /movies
#     tvPath: /tv
#     musicPath: /music
#     movies4kPath: /movies-4k
#     tv4kPath: /tv-4k
#
# Secrets
# -------
# API key Secrets (sonarr-api-key, radarr-api-key, etc.) are created
# automatically by the operator the first time each ServarrApp is reconciled.
# For Sonarr, Radarr, Lidarr, and Prowlarr the operator also injects the key
# as an environment variable so the app uses it from first startup.  Overseerr
# manages its key independently; after it starts, retrieve the key from
# Settings → General and update the Secret:
#   kubectl patch secret overseerr-api-key -p '{"stringData":{"api-key":"<key>"}}'
#
# The Transmission auth Secret must be created manually before applying since
# it contains user credentials chosen by you, not generated by an app:
#   kubectl create secret generic transmission-auth \
#     --from-literal=username=admin --from-literal=password=changeme
apiVersion: servarr.dev/v1alpha1
kind: MediaStack
metadata:
  name: media
spec:

  # ─────────────────────────────────────────────────────────────────────────
  # In-cluster NFS server (1 Ti PVC, auto-injected into all apps).
  # Remove this block entirely to get the same default behaviour.
  # ─────────────────────────────────────────────────────────────────────────
  nfs:
    storageSize: 1Ti
    storageClass: longhorn    # omit to use the cluster default

  # ─────────────────────────────────────────────────────────────────────────
  # Stack-wide defaults — inherited by every app unless overridden per-app.
  # ─────────────────────────────────────────────────────────────────────────
  defaults:
    uid: 1000
    gid: 1000

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1Gi

    env:
      - name: TZ
        value: America/New_York

  apps:

    # ── Media servers ────────────────────────────────────────────────────────
    # Plex and Jellyfin receive all five media mounts automatically.

    - app: Plex
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "4"
          memory: 4Gi
      gpu:
        intel: 1    # Intel Quick Sync hardware transcoding

    - app: Jellyfin
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "4"
          memory: 4Gi
      gpu:
        intel: 1    # Intel Quick Sync hardware transcoding

    # ── Download clients ─────────────────────────────────────────────────────
    # SABnzbd and Transmission receive all media mounts automatically so that
    # managers can hardlink completed files into the library (same filesystem).

    - app: Sabnzbd
      appConfig:
        sabnzbd:
          # Hostnames accepted for reverse-proxy connections.
          hostWhitelist:
            - sabnzbd.media.svc.cluster.local
            - sabnzbd.example.com
          # Automatically unpack zip/rar archives on completion.
          tarUnpack: true

    - app: Transmission
      appConfig:
        transmission:
          auth:
            secretName: transmission-auth
          peerPort:
            port: 51413
            hostPort: true    # Bind port directly on the node for inbound peers
          settings:
            ratio-limit-enabled: true
            ratio-limit: 2.0  # Seed to 2:1 then stop

    # ── Media managers ───────────────────────────────────────────────────────
    # split4k: true creates two instances — standard and 4K.  Each instance
    # receives the same container mount paths (/tv, /movies) so Sonarr/Radarr
    # configuration is identical.  Internally the operator maps the 4K
    # instance to a separate NFS directory (/nfsshare/tv-4k, /nfsshare/movies-4k).
    # This lets Overseerr target the standard and 4K instances independently
    # without any special app-level configuration.

    - app: Sonarr
      split4k: true
      apiKeySecret: sonarr-api-key
      backup:
        enabled: true
        schedule: "0 3 * * *"
        retentionCount: 7
      prowlarrSync:
        enabled: true
      # 4K encode processing is heavier — give the 4K instance more headroom.
      split4kOverrides:
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: "4"
            memory: 4Gi

    - app: Radarr
      split4k: true
      apiKeySecret: radarr-api-key
      backup:
        enabled: true
        schedule: "0 3 * * *"
        retentionCount: 7
      prowlarrSync:
        enabled: true
      split4kOverrides:
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: "4"
            memory: 4Gi

    - app: Lidarr
      apiKeySecret: lidarr-api-key
      backup:
        enabled: true
        schedule: "0 3 * * *"
        retentionCount: 7
      prowlarrSync:
        enabled: true

    # ── Indexers ─────────────────────────────────────────────────────────────

    - app: Prowlarr
      # Central indexer hub.  prowlarrSync (set per-app above) pushes search
      # provider configuration to Sonarr, Radarr, and Lidarr automatically.
      apiKeySecret: prowlarr-api-key
      backup:
        enabled: true
        schedule: "0 2 * * *"
        retentionCount: 7

    - app: Jackett
      # Legacy indexer proxy retained for any trackers not yet available in
      # Prowlarr's Cardigann format.
      # Remove once migration to Prowlarr is complete.

    # ── Request management ────────────────────────────────────────────────────

    - app: Overseerr
      # Auto-discovers Sonarr and Radarr instances in the same namespace via
      # overseerrSync.  The appConfig below tells the operator which quality
      # profiles and root folders to use when registering each discovered
      # server, including the 4K variants created by split4k above.
      apiKeySecret: overseerr-api-key
      overseerrSync:
        enabled: true
      appConfig:
        overseerr:
          sonarr:
            profileId: 1
            profileName: "HD-1080p"
            rootFolder: /tv
            enableSeasonFolders: true
            fourK:
              profileId: 2
              profileName: "2160p-HDR"
              rootFolder: /tv
              enableSeasonFolders: true
          radarr:
            profileId: 1
            profileName: "HD-1080p"
            rootFolder: /movies
            minimumAvailability: released
            fourK:
              profileId: 2
              profileName: "2160p-HDR"
              rootFolder: /movies
              minimumAvailability: released

    # ── Monitoring / utilities ────────────────────────────────────────────────

    - app: Tautulli
      # Plex activity monitor — only talks to the Plex API.

    - app: Maintainerr
      # Automated media cleanup.  Not in the auto-injection list, so media
      # mounts are declared explicitly.
      persistence:
        nfsMounts:
          - name: movies
            server: media-nfs-server.media.svc.cluster.local
            path: /nfsshare/movies
            mountPath: /movies
          - name: tv
            server: media-nfs-server.media.svc.cluster.local
            path: /nfsshare/tv
            mountPath: /tv

    - app: SshBastion
      # Secure SFTP access for manual file management.  Not in the
      # auto-injection list, so mounts are declared explicitly.
      persistence:
        nfsMounts:
          - name: movies
            server: media-nfs-server.media.svc.cluster.local
            path: /nfsshare/movies
            mountPath: /movies
          - name: tv
            server: media-nfs-server.media.svc.cluster.local
            path: /nfsshare/tv
            mountPath: /tv
          - name: music
            server: media-nfs-server.media.svc.cluster.local
            path: /nfsshare/music
            mountPath: /music
      appConfig:
        sshBastion:
          mode: sftp
          users:
            - name: mediaadmin
              uid: 1000
              gid: 1000
              publicKeys: |
                ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... mediaadmin@workstation
