# Minimal Lidarr — music management
apiVersion: servarr.dev/v1alpha1
kind: ServarrApp
metadata:
  name: lidarr
spec:
  app: Lidarr
  persistence:
    volumes:
      - name: downloads
        mountPath: /downloads
        size: 50Gi
