apiVersion: servarr.dev/v1alpha1
kind: MediaStack
metadata:
  name: media
spec:
  defaults:
    adminCredentials:
      secretName: smoke-admin
  apps:
    - app: Jellyfin
    - app: Transmission
    - app: Sonarr
