mod client;
pub mod health;
pub mod jellyfin;
pub mod k8s;
pub mod plex;
pub mod overseerr;
pub mod prowlarr;
pub mod sabnzbd;
pub mod servarr_v3;
pub mod transmission;

pub use client::{ApiError, HttpClient};
pub use health::HealthCheck;
pub use jellyfin::JellyfinClient;
pub use k8s::{SecretError, read_secret_key};
pub use plex::PlexClient;
pub use overseerr::OverseerrClient;
pub use prowlarr::ProwlarrClient;
pub use sabnzbd::SabnzbdClient;
pub use servarr_v3::ServarrClient;
pub use transmission::TransmissionClient;
